language: "python"

python: "2.7"

env:
    - "TOX_ENV=pyflakes"
    - "TOX_ENV=py27"
    - "TOX_ENV=pypy"

install:
    - "pip install tox"

script:
    - "tox -e ${TOX_ENV}"

notifications:
    email: false
